--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/ethaniccc/Mockingbird
build-by-default: true
branches:
- master
- stable
projects:
  Mockingbird:
    path: ""
    libs:
      - src: jojoe77777/FormAPI/libFormAPI
        version: ^1.3.0
        branch: master
...
